---
- name: "PLAYBOOK        : Start Playbook for PiStack."
  hosts: servers
  become: yes
  
# We use Ping in case facts gathering is switched off
  pre_tasks:
    - name: "PLAYBOOK        : Ping using Root User."
      ping: 

# We use dist-update since we are using tumbleweed
  tasks:
    - name: "PLAYBOOK        : Distro Update." 
      include_role:
        name: ro_distro_update
