---
- name: "PLAYBOOK        : Start Playbook for PiStack."
  hosts: servers
  become: yes
  
  pre_tasks:
    - name: "PLAYBOOK        : Ping using Root User."
      ping: 

# We use dist-update since we are using tumble weed
  tasks:
    - name: "PLAYBOOK        : Update all packages on OpenSUSE/SUSE Linux."
      community.general.zypper:
        name: '*'
        allow_vendor_change: true
        state: dist-upgrade

    - name: "PLAYBOOK        : Check if a reboot is needed on all SUSE/OpenSUSE based servers."
      register: linux_reboot_required_file
      stat: path=/boot/do_purge_kernels get_md5=no

    - name: "PLAYBOOK        : Reboot the SUSE/OpenSUSE box if kernel updated."
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates."
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: linux_reboot_required_file.stat.exists
