---
- name: "PLAYBOOK        : Start Playbook for PiStack."
  hosts: servers
  become: yes
  
  pre_tasks:
    - name: "PLAYBOOK        : Ping using Root User."
      ping: 

# We use dist-update since we are using tumbleweed
  tasks:
    - name: "PLAYBOOK        : Ping using Root User." 
      include_role:
        name: ro_distro_update.yml
