---
- name: "PLAYBOOK        : Start Playbook for PiStack."
  hosts: server

  pre_tasks:
    - name: "PLAYBOOK        : Ping using Root User."
      ping: 

  tasks:
    - name: "PLAYBOCK        : Mange Ansible Group."
      group: 
        name: ansible
        gid: 20020
        state: present

    - name: "PLAYBOCK        : Mange Ansible User."
      user:
        name: ansible
        group: ansible
        home: 
        uid: 20020
        state: present
            
    - name: "PLAYBOCK        : Mange Sudoers for Ansible User."
      lineinfile:
        path: /etc/sudoers.d/ansible
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        mode: 0440
        create: yes
        state: present

    - name: "PLAYBOCK        : Set Authorized Key."
      authorized_key:
        user: ansible
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
      ignore_errors: "{{ ansible_check_mode }}"
# For openSuse use systemd ; got it by trying LOL
    - name: "PLAYBOCK        : Set hostname."
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: systemd

    - name: "PLAYBOOK        : Set TimeZone."
      community.general.timezone:
        name: Europe/Zurich

    - name: "PLAYBOOK        : Set Keybord."
      ansible.builtin.command: "yast2 keyboard set 'layout=german-ch'"