---
- name: "PLAYBOOK        : Start Playbook for PiStack."
  hosts: server
  gather_facts: no  
  vars:
    ansible_host_key_checking: false

  tasks:
    - name: "PLAYBOOK        : Assure Accessability  to Remote Server using Ansible User."
      block:
        - name: "PLAYBOOK        : Ping using regular Ansible User."
          ping:

        - name: Force a failure 
          ansible.builtin.command: /bin/false

      rescue:
        - name: "PLAYBOOK        : Ping using Root User."
          remote_user: root
          ping: