---
- name: "PLAYBOOK        : Start Playbook for PiStack."
  hosts: all

# This is optional, but usefull wen not gathering acts
  pre_tasks:
    - name: "PLAYBOOK        : Ping using Root User."
      ping: 

  tasks:
# For openSuse use systemd ; got it by trying LOL
    - name: "PLAYBOOK        : Set hostname."
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: systemd

    - name: "PLAYBOOK        : Set TimeZone."
      ansible.builtin.timezone:
        name: Europe/Zurich

    - name: "PLAYBOOK        : Set Keybord."
      ansible.builtin.command: "yast2 keyboard set 'layout=german-ch'"

    - name: "PLAYBOOK        : Set a message of the day."
      ansible.builtin.copy:
        dest: /etc/motd 
        src: "etc/motd/{{ inventory_hostname }}"
        owner: root
        group: root
        mode: 0644

    - name: "PLAYBOOK        : Mange Ansible Group."
      ansible.builtin.group: 
        name: ansible
        gid: 20020
        state: present

    - name: "PLAYBOOK        : Mange Ansible User."
      ansible.builtin.user:
        name: ansible
        group: ansible
        home: 
        uid: 20020
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_comment: "Generated by Ansible Playbook 'pb_init_pistack'."
        state: present

    - name: "PLAYBOOK        : Mange Sudoers for Ansible User."
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        mode: 0440
        create: yes
        state: present

    - name: "PLAYBOOK        : Set Authorized Key."
      ansible.builtin.authorized_key:
        user: ansible
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
      ignore_errors: "{{ ansible_check_mode }}"

    - name: "PLAYBOOK        : Mange Root User Password."
      ansible.builtin.user:
        name: root
        password: "{{ 'linux' | password_hash('sha512') }}"
        update_password: always
        state: present
