---
- name: "PLAYBOOK        : Start Playbook to Shutdown Full PiStack."
  hosts: all

  tasks:
    - name: "PLAYBOOK        : Shutdown in one Minute."
      become: yes
      ansible.builtin.command: "shutdown -h +1"